language: ruby
sudo: false
cache: bundler

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3

env:
  - rails=3.2.0
  - rails=4.1.0
  - rails=4.2.0
  - rails=5.0.1

gemfile:
  - gemfiles/Gemfile.mongoid2.rb
  - gemfiles/Gemfile.mongoid3.rb
  - gemfiles/Gemfile.mongoid4.rb
  - gemfiles/Gemfile.mongo_mapper.rb
  - gemfiles/Gemfile.mongoid6.rb

services:
  - mongodb

matrix:
  exclude:
    - env: rails=3.2.0
      rvm: 2.2

    - gemfile: gemfiles/Gemfile.mongoid2.rb
      env: rails=4.1.0
    - gemfile: gemfiles/Gemfile.mongoid2.rb
      env: rails=4.2.0

    - gemfile: gemfiles/Gemfile.mongoid3.rb
      env: rails=4.1.0
    - gemfile: gemfiles/Gemfile.mongoid3.rb
      env: rails=4.2.0

    - gemfile: gemfiles/Gemfile.mongoid4.rb
      env: rails=3.2.0

    - gemfile: gemfiles/Gemfile.mongoid6.rb
      env: rails=5.0.1
      rvm: 2.3
